spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/seminars
    username: seminars
    password: seminars

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: yfu_seminars
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true

  http:
    converters:
      preferred-json-mapper: jackson

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Europe/Berlin
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    locale: de_DE
    serialization-inclusion: non_empty
    serialization:
      write-dates-as-timestamps: false
    mapper:
      sort-properties-alphabetically: true
      default-view-inclusion: false

azure:
  activedirectory:
    client-secret: Sa3gzI2aeKxFqdqfLbhxNVmvtLy4RESBBZFMSXV0Kpo=
    client-id: 7c2eb271-b1d9-43a4-9b34-1261bdce9cea
    active-directory-groups: Seminars

server:
  port: 8080
  servlet:
    contextPath: /api

cors:
  allowedOrigins:
  - "http://localhost:8080"
  - "https://methodendb.yfu.alexmsenger.de"
  allowedMethods:
  - GET
  - POST
  - PUT
  - PATCH
  - DELETE
  - OPTIONS
  allowedHeaders:
  - Authorization
  - Content-Type
  - X-Flow-ID
  - Accept
  exposedHeaders:
  - X-Flow-ID
  maxAge: 3600
  allowCredentials: true

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db:5432/seminars